import Model, { attr } from '@ember-data/model';

export default class RepositoryModel extends Model {
  @attr('boolean') declare allow_forking: boolean;
  @attr('string') declare archive_url: string;
  @attr('boolean') declare archived: boolean;
  @attr('string') declare assignees_url: string;
  @attr('string') declare blobs_url: string;
  @attr('string') declare branches_url: string;
  @attr('string') declare clone_url: string;
  @attr('string') declare collaborators_url: string;
  @attr('string') declare comments_url: string;
  @attr('string') declare commits_url: string;
  @attr('string') declare compare_url: string;
  @attr('string') declare contents_url: string;
  @attr('string') declare contributors_url: string;
  @attr('date') declare created_at: Date;
  @attr('string') declare default_branch: string;
  @attr('string') declare deployments_url: string;
  @attr('string') declare description: string;
  @attr('boolean') declare disabled: boolean;
  @attr('string') declare downloads_url: string;
  @attr('string') declare events_url: string;
  @attr('boolean') declare fork: boolean;
  @attr('number') declare forks: number;
  @attr('number') declare forks_count: number;
  @attr('string') declare forks_url: string;
  @attr('string') declare full_name: string;
  @attr('string') declare git_commits_url: string;
  @attr('string') declare git_refs_url: string;
  @attr('string') declare git_tags_url: string;
  @attr('string') declare git_url: string;
  @attr('boolean') declare has_downloads: boolean;
  @attr('boolean') declare has_issues: boolean;
  @attr('boolean') declare has_pages: boolean;
  @attr('boolean') declare has_projects: boolean;
  @attr('boolean') declare has_wiki: boolean;
  @attr('string') declare homepage: string;
  @attr('string') declare hooks_url: string;
  @attr('string') declare html_url: string;
  @attr('boolean') declare is_template: boolean;
  @attr('string') declare issue_comment_url: string;
  @attr('string') declare issue_events_url: string;
  @attr('string') declare issues_url: string;
  @attr('string') declare keys_url: string;
  @attr('string') declare labels_url: string;
  @attr('string') declare language: string;
  @attr('string') declare languages_url: string;
  @attr() license: unknown;
  @attr('string') declare merges_url: string;
  @attr('string') declare milestones_url: string;
  @attr() mirror_url: unknown;
  @attr('string') declare name: string;
  @attr('string') declare node_id: string;
  @attr('string') declare notifications_url: string;
  @attr('number') declare open_issues: number;
  @attr('number') declare open_issues_count: number;
  @attr() owner: unknown;
  @attr('boolean') declare private: boolean;
  @attr('string') declare pulls_url: string;
  @attr('date') declare pushed_at: Date;
  @attr('string') declare releases_url: string;
  @attr('number') declare size: number;
  @attr('string') declare ssh_url: string;
  @attr('number') declare stargazers_count: number;
  @attr('string') declare stargazers_url: string;
  @attr('string') declare statuses_url: string;
  @attr('string') declare subscribers_url: string;
  @attr('string') declare subscription_url: string;
  @attr('string') declare svn_url: string;
  @attr('string') declare tags_url: string;
  @attr('string') declare teams_url: string;
  @attr() topics: unknown;
  @attr('string') declare trees_url: string;
  @attr('date') declare updated_at: Date;
  @attr('string') declare url: string;
  @attr('string') declare visibility: string;
  @attr('number') declare watchers: number;
  @attr('number') declare watchers_count: number;
}
